name: Bale Weather Bot

on:
  schedule:
    - cron: "0 */4 * * *" # هر ۴ ساعت یکبار
  workflow_dispatch: # قابلیت اجرای دستی برای تست

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # نسخه دقیق برای پایداری

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run Weather Bot
        env:
          BALE_TOKEN: ${{ secrets.BALE_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python weather.py
